name: 03 - Schedule

on:
  schedule:
  # Tarea cron explicada:
  # minuto -> 0
  # hora -> 9
  # dia del mes -> *
  # cualquier mes -> *
  # dia de la semana -> 1 (lunes)
    - cron: '0 9 * * 1'
  workflow_dispatch: # Ejecución de prueba

jobs:
  saludo:
    runs-on: ubuntu-24.04
    steps:
      - name: Saludar
        run: echo "Hola desde GitHub Actions!"